# Generated by Django 4.2.14 on 2024-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContrattoTelefonico',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('data_attivazione', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('minuti_residui', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credito_residuo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('codice', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.DateField()),
                ('associata_a', models.IntegerField(blank=True, null=True)),
                ('era_associata_a', models.IntegerField(blank=True, null=True)),
                ('data_attivazione', models.DateField(blank=True, null=True)),
                ('data_disattivazione', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('effettuata_da', models.IntegerField()),
                ('data', models.DateField()),
                ('ora', models.CharField(max_length=5)),
                ('durata', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='telefonata',
            constraint=models.UniqueConstraint(fields=('counter', 'effettuata_da'), name='unique_telefonata'),
        ),
    ]
