# Generated by Django 4.2.14 on 2024-07-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sim_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMAttiva',
            fields=[
                ('codice', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('associata_a', models.IntegerField(blank=True, null=True)),
                ('era_associata_a', models.IntegerField(blank=True, null=True)),
                ('data_attivazione', models.DateField(blank=True, null=True)),
                ('data_disattivazione', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIMDisattiva',
            fields=[
                ('codice', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('associata_a', models.IntegerField(blank=True, null=True)),
                ('era_associata_a', models.IntegerField(blank=True, null=True)),
                ('data_attivazione', models.DateField(blank=True, null=True)),
                ('data_disattivazione', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIMNonAttiva',
            fields=[
                ('codice', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('associata_a', models.IntegerField(blank=True, null=True)),
                ('era_associata_a', models.IntegerField(blank=True, null=True)),
                ('data_attivazione', models.DateField(blank=True, null=True)),
                ('data_disattivazione', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SIM',
        ),
        migrations.AlterField(
            model_name='contrattotelefonico',
            name='credito_residuo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrattotelefonico',
            name='minuti_residui',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='telefonata',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
